# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chatgptdash < Formula
  desc ""
  homepage "https://github.com/dash2701/chatgptdash"
  version "0.5"

  on_macos do
    url "https://github.com/Dash2701/chatgptdash/releases/download/v0.5/chatgptdash_0.5_darwin_all.tar.gz"
    sha256 "1ea90910cfcc9d5cc438966d160f7eaf6d8087d53f12602ad5b0030150a9d865"

    def install
      bin.install "chatgptdash"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dash2701/chatgptdash/releases/download/v0.5/chatgptdash_0.5_linux_arm64.tar.gz"
      sha256 "80e0f86ccd34d476fd201abd338ecf924a2492678c636a37bc123450fb88da6f"

      def install
        bin.install "chatgptdash"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Dash2701/chatgptdash/releases/download/v0.5/chatgptdash_0.5_linux_amd64.tar.gz"
      sha256 "0b98a4903bbc4053b294cdabf2700227dfd1193ce9645731e83ac6a7b230f806"

      def install
        bin.install "chatgptdash"
      end
    end
  end
end
