# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Chatgptdash < Formula
  desc ""
  homepage "https://github.com/dash2701/chatgptdash"
  version "0.3.3"

  on_macos do
    url "https://github.com/Dash2701/chatgptdash/releases/download/v0.3.3/chatgptdash_0.3.3_darwin_all.tar.gz"
    sha256 "035c8fb2fa8835bb499be7d700c4ea77b80f5055ca196b2fc73747d762da4588"

    def install
      bin.install "chatgptdash"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dash2701/chatgptdash/releases/download/v0.3.3/chatgptdash_0.3.3_linux_arm64.tar.gz"
      sha256 "b6c38f2e5bd9d12f2679593672551e16dabcdefc11f2ab80973c6fcdc5c9147f"

      def install
        bin.install "chatgptdash"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Dash2701/chatgptdash/releases/download/v0.3.3/chatgptdash_0.3.3_linux_amd64.tar.gz"
      sha256 "af82e051f1d8dfc75575c504decab7244e853f2ec7046b4d0b7f5db694bf55da"

      def install
        bin.install "chatgptdash"
      end
    end
  end
end
